### ISSUE TITLE
'io-ts' and 'io-ts-types' are missing

### ISSUE THREAD

**Issue by scink** [devex-web-frontend/remote-data-ts#23]
because of **remote-data-io.ts** import in **index.ts** packages **io-ts** and **io-ts-types** became required. but they are in **peerDependencies** and NPM doesn't install them. that forces to install unnecessary for project packages manually. removing **index.ts** will fix it

**Comment by sutarmin** [comment]
`main` in `package.json` must be returned back to `dist/remote-data.js`. `io-ts` type must be imported from `remote-data-ts/remote-data-io` directly. This will be a breaking change. /cc @mlegenhausen

**Comment by raveclassic** [comment]
This is a regression after #19

**Comment by mlegenhausen** [comment]
@raveclassic I like the third solution.

**Comment by raveclassic** [comment]
So after a brief discussion it was decided to move peer-dependencies to dependencies.
@scink Could you update #24 (and rename) accordingly?

**Comment by scink** [comment]
sure
