### ISSUE TITLE
Add monocle-ts Optional

### ISSUE THREAD

**Issue by mlegenhausen** [devex-web-frontend/remote-data-ts#25]
What do you think about adding support for `monocle-ts` via an `Optional`?

```ts
const RemoteDataOptional = <L, R>() => new Optional<RemoteData<L, R>, R>(
  s => s.toOption(),
  a => s => s.fold(s, s, () => s, () => success(a))
);
```

**Comment by raveclassic** [comment]
Thanks for suggestion and sorry for such long answer. Unfortunately I don't think it's a good idea to add `monocle-ts` to dependencies. Yeah I'm ok with `io-ts` because it is related to the data structure (serialization/deserialization). But I don't see any relation to optics especially if the suggested function is trivial.

**Comment by anthonyjoeseph** [comment]
> I don't see any relation to optics

Isn't RemoteData an ADT? Aren't ADT's [directly related to optics](https://kubuszok.com/2018/adt-through-the-looking-glass/)?

> I'm ok with `io-ts` because it is related to the data structure

Isn't monocle-ts [entirely dedicated](https://github.com/gcanti/monocle-ts#motivation) to data structure?

> especially if the suggested function is trivial

Aren't most optics functions ['trivial'](https://github.com/sledorze/morphic-ts/blob/ae5fa8dbece8bd6aca363a617a30d9a10229ed37/packages/morphic-adt/src/monocle.ts#L51) by nature?

**Comment by sutarmin** [comment]
hey, @anthonyjoeseph , thanks for your thoughts! No doubts it's a nice thing to have such helper utilities, but I agree with @raveclassic here that this is not related to core RemoteData logic and should be placed in some external library/end code.

**Comment by anthonyjoeseph** [comment]
I understand that. Any thoughts about what such an external library might look like? Maybe something like [io-ts-extras](https://github.com/mmkal/ts/tree/main/packages/io-ts-extra)? It seems too specific for [fp-ts-contrib](https://github.com/gcanti/fp-ts-contrib).

Maybe we need a `monocle-ts-contrib`. Does something like this exist already?

Forgive me, I don't mean for this thread to become too off topic, this just seems to me like a potentially common use case (deeply nested remote data could go inside redux state, etc)

**Comment by anthonyjoeseph** [comment]
FWIW both the [Elm](https://package.elm-lang.org/packages/krisajenkins/remotedata/latest/RemoteData#prism) and [Purescript](https://pursuit.purescript.org/packages/purescript-remotedata/2.1.1/docs/Network.RemoteData#v:_NotAsked) versions of RemoteData include optics (and the Elm interface even avoids a dependency)
