### ISSUE TITLE
Possible bug in remote-data-io.ts

### ISSUE THREAD

**Issue by gcanti** [devex-web-frontend/remote-data-ts#31]
I think I found a bug while trying to upgrade this library to fp-ts@2

[Here](https://github.com/devex-web-frontend/remote-data-ts/blob/9d2d0f2bec494a033f10f2659eb456c0f781dcdd/src/remote-data-io.ts#L119)

`JSONProgress.encode` outputs a `{ loaded: number; total: number | null; } | null` but should be a `RemoteProgress | null` and `RemoteProgress` is defined as

```ts
export type RemoteProgress = {
  loaded: number;
  total: Option<number>;
};
```

Repro

- install `io-ts-types@latest`
- open `src/remote-data-io.ts` in VSCode or try to compile the project, shouldn't type check

**Comment by raveclassic** [comment]
Thanks @gcanti 
Yeah, this is because `JSONRemoteData` refers to `RemoteProgress` which uses `Option` in `total` field. Looks like this result in an error with latest `io-ts-types`. I'll fix it and release a minor with updated versions of all related libs.
