### ISSUE TITLE
fp-ts@2

### ISSUE THREAD

**Issue by mlegenhausen** [devex-web-frontend/remote-data-ts#33]
Are there any plans to port this library to `fp-ts@2`? I could provide a pull request to make it both `fp-ts@1` and `fp-ts@2` compatable.

**Comment by raveclassic** [comment]
Hi @mlegenhausen, sure we have plans to upgrade to `fp-ts@2.0`. However we don't have free time right now to do it.

related https://github.com/devex-web-frontend/dx-platform/issues/137
