### ISSUE TITLE
Add progress to RemotePending

### ISSUE THREAD

**Issue by OliverJAsh** [devex-web-frontend/remote-data-ts#9]
I want to record the progress of an (upload) request, however currently `RemotePending` does not store any value for itself.

Example of a remote data type which has this: https://github.com/cyclejs-community/cycle-remote-data

https://github.com/cyclejs-community/cycle-remote-data#whencases-casest-u-u

Related https://github.com/krisajenkins/remotedata/issues/25

**Comment by raveclassic** [comment]
@OliverJAsh This looks more like success state: 
```typescript
type Loading = { type: 'progress', progress: number }
type Resolved<A> = { type: 'resolved', value: A }
type Data<A> = Loading | Resolved<A>
type RD<A> = RemoteData<Data<A>>
```

Conceptually `RemotePending` describes initial loading of some piece of data and tracking progress IMO relates more to resolved (`RemoteSuccess`) state.

**Comment by OliverJAsh** [comment]
> Conceptually RemotePending describes initial loading of some piece of data

That initial loading will have a progress though?

For context, I want to use this to track the progress of a file upload. The request is pending whilst the file uploads—it could still fail.

**Comment by raveclassic** [comment]
@OliverJAsh Makes sense... Still it will be a massive breaking change for our codebase to add an argument to `pending`. What do you think about adding optional argument to `RemotePending` constructor defaulting to zero and introducing new helper `progress(value: number): RemotePending`?

```typescript
class RemotePending<L, A> {
  constructor(readonly progress: number = 0) { }
}
const progress = <L, A>(progress: number): RemotePending<L, A> => new RemotePending(progress)
```

Also we should think about `Apply` instance (and others). How such pendings with progress will be combined? Normalizing all progresses to 1? How should `sequence`/`traverse` behave for lists of `RemoteData`?

**Comment by OliverJAsh** [comment]
> What do you think about adding optional argument to RemotePending constructor defaulting to zero and introducing new helper progress(value: number): RemotePending?

Good idea.

Do we need to make it explicit that the progress is for uploading (as it's typically derived from `xhr.upload.onprogress`, which emits `ProgressEvent`)? Perhaps:

``` ts
type RemotePendingUpload = { progress: { loaded: number } };

class RemotePending<L, A> {
  constructor(readonly upload: Option<RemotePendingUpload> = Option.none()) { }
}
```

**Comment by raveclassic** [comment]
@OliverJAsh Progress can also be tracked for downloading, not only uploading, so I'd rather stick to `progress: number` argument. Is there anything else that should be tracked except this number?

**Comment by OliverJAsh** [comment]
True, in that case, what about a request where we want to track the progress of both uploading and downloading? We need two pieces of state I think?

Maybe we can also include the other properties of `ProgressEvent`: https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent

**Comment by raveclassic** [comment]
> what about a request where we want to track the progress of both uploading and downloading? 

Could you provide an example of such request?

> Maybe we can also include the other properties of ProgressEvent

This doesn't play well with `RemotePending` default value. `Option` looks more like a crutch.

**Comment by OliverJAsh** [comment]
> Option looks more like a crutch.

Sorry but can you elaborate?

> Could you provide an example of such request?

I can't, sorry! Make it could be confusing if there was one `progress` state, that could be either the upload or download, depending on the implementation.

**Comment by raveclassic** [comment]
> Sorry but can you elaborate?

I mean that if you already are in a pending state then `progress === none` makes no sense.

**Comment by raveclassic** [comment]
@OliverJAsh What do you think about making `total` an `Option` if `lengthComputable` is false?
```typescript
type RemoteProgressEvent = {
  loaded: number;
  total: Option<number>;
}
class RemotePending<L, A> {
  constructor(readonly progress: RemoteProgressEvent = { loaded: 0 }) { }
}
const progress = <L, A>(progress: RemoteProgressEvent): RemotePending<L, A> => new RemotePending(progress)
```

**Comment by OliverJAsh** [comment]
@raveclassic Sounds sensible to me.

I still wonder if we need to allow for upload/download progress simultaneously, or at least to help disambiguate whether the progress signals an upload or download. 🤔 

> I mean that if you already are in a pending state then progress === none makes no sense.

Hmm, I see your point. OTOH, I don't think all requests emit a `ProgressEvent` (although I might be wrong), in which case I wouldn't expect a value.

**Comment by raveclassic** [comment]
> I still wonder if we need to allow for upload/download progress simultaneously, or at least to help disambiguate whether the progress signals an upload or download. 

I think it's not responsibility of RemoteData but of the process itself.

> OTOH, I don't think all requests emit a ProgressEvent (although I might be wrong), in which case I wouldn't expect a value.

Agree, you are right since RemoteData is not only about XHR.

Summing up, is the following correct?
```typescript
type RemoteProgress =  {
  loaded: number;
  total: Option<number>
}
class RemotePending<L, A> {
  contructor(readonly progress: Option<RemoteProgress> = none) { }
}
const progress = <L, A>(progress: RemoteProgress): RemotePending<L, A> => new RemotePending(progress)
```

Would you like to open PR?

**Comment by raveclassic** [comment]
Here're my observations, need help with **???**:

`none + some({ loaded: 123 }) = some({ loaded: 123 })`
`some({ loaded: 1, total: none }) + some({ loaded: 2, total: none }) = some({ loaded: 3, total: none })`
`some({ loaded: 1, total: some(10) }) + some({ loaded: 2, total: none }) `= **???**

and the most tricky
```typescript
const a = some({ loaded: 1, total: some(10) })
const b = some({ loaded: 3, total: some(20) })
const aLoaded = a.loaded
const bLoaded = b.loaded
const aTotal = a.total.value
const bTotal = b.total.value
const resultTotal = aTotal + bTotal // I guess the values should be added here, right?
const resultLoaded 
  = (aLoaded / (resultTotal / aTotal)) / resultTotal + (bLoaded / (resultTotal / bTotal)) / resultTotal 
  = (aLoaded * aTotal + bLoaded * bTotal) / resultTotal * resultTotal
  // correct?
```

/cc @sutarmin @igoralekseev @mankdev

**Comment by sutarmin** [comment]
I think summing up proportionally would be the best strategy here.
??? looks like `{ loaded: 3, total: none }`. Not enough data to assume smth better.

**Comment by raveclassic** [comment]
@sutarmin Makes sense
@OliverJAsh Is it acceptable for you?

**Comment by OliverJAsh** [comment]
I'm not sure to be honest. I haven't required that ability yet.
